export const state = {
    field: {
        company_name: "",
        occupation: "",
        position: "",
        industry: "",
        office_address: "",
        company_contact: "",
        income: "",
        salary_date: "",
        year_service: "",
        e_name_1: "",
        e_relationship_1: "",
        e_mobile_1: "",
        e_name_2: "",
        e_relationship_2: "",
        e_mobile_2: "",
    },
    isLoading: false,
    errors: null,
}